const PRODUCTS=[
{slug:'love-coupon-book',name:'The Love Coupon Book',category:'Gifts',price:900,description:'A playful, printable coupon book of little promises for your favorite person — one design, endlessly personal.',cover:'love-coupon-book/cover.png'},
{slug:'save-the-date',name:'Save the Date',category:'Stationery',price:1200,description:'An elegant Save the Date card to give your guests the first glimpse of your wedding day.',cover:'save-the-date/cover.png'},
{slug:'invitation-suite',name:'Invitation Suite',category:'Stationery',price:1800,description:'A classic wedding invitation suite with a coordinating RSVP card, prepared for professional printing.',cover:'invitation-suite/cover.png'},
{slug:'wedding-day-set',name:'Wedding Day Set',category:'Stationery',price:2200,description:'Everything for the day itself — programs, menus and signage in one coordinated set.',cover:'wedding-day-set/cover.png'},
{slug:'monogram-pack',name:'Monogram & Crest Pack',category:'Designers',price:1500,description:'A set of custom monogram and crest designs to carry your initials across every piece of your wedding stationery.',cover:'monogram-pack/cover.png'},
{slug:'welcome-sign-set',name:'Welcome & Guest Book Sign Set',category:'Ceremony',price:1600,description:'Large-format welcome and guest book signs in four coordinating styles.',cover:'welcome-sign-set/cover.png'},
{slug:'thank-you-cards',name:'Thank You Cards',category:'Stationery',price:1000,description:'Four beautifully designed thank you card styles to send your gratitude after the big day.',cover:'thank-you-cards/cover.png'},
{slug:'invitation-suite-floral',name:'Floral Photo Invitation Suite',category:'Featured Destinations',price:1900,description:'A romantic invitation and RSVP card built directly on a floral flat-lay photograph.',cover:'invitation-suite-floral/cover.png'},
{slug:'tuscany-set',name:'Blush Rose Suite',category:'Featured Destinations',price:2400,description:'Invitation, menu and table number in a watercolor blush rose design — three matching pieces, sold as a set.',cover:'tuscany-set/cover.png'},
{slug:'rosewood-set',name:'Rosewood Garden Suite',category:'Featured Destinations',price:2400,description:'Invitation, menu and table number in a watercolor peony and rose design with a scalloped gold border.',cover:'rosewood-set/cover.png'},
{slug:'villa-belvedere-set',name:'Villa Belvedere Suite',category:'Featured Destinations',price:2400,description:'Invitation, menu and table number built on a photorealistic peony and rose bouquet, with a thin gold border.',cover:'villa-belvedere-set/cover.png'}
];
const bySlug=Object.fromEntries(PRODUCTS.map(p=>[p.slug,p]));
const money=c=>'$'+(c/100).toFixed(2);
const img=p=>'store/static/products/'+p.cover;
let cart=JSON.parse(localStorage.getItem('loveforlove-cart')||'[]').filter(s=>bySlug[s]);
function saveCart(){localStorage.setItem('loveforlove-cart',JSON.stringify(cart));document.getElementById('cart-count').textContent=cart.length;}
function productTile(p){return `<a class="p-tile" href="#product/${p.slug}"><div class="thumb"><img src="${img(p)}" alt="${p.name}"></div><div class="name">${p.name}</div><div class="price">${money(p.price)}</div></a>`}
function smallTile(p){return `<div><a class="s-tile" href="#product/${p.slug}"><img src="${img(p)}" alt="${p.name}"></a><div class="tile-cap">${p.name}<br><span class="tile-price">${money(p.price)}</span></div></div>`}
function renderHome(){const featured=PRODUCTS.filter(p=>p.category==='Featured Destinations').slice(0,8);const stationery=PRODUCTS.filter(p=>p.category==='Stationery').slice(0,8);const curated=PRODUCTS.filter(p=>!['Featured Destinations','Stationery'].includes(p.category)).slice(0,8);document.getElementById('home-grids').innerHTML=[['Featured Destinations',featured],['Shop Stationery',stationery],['Curated Collections',curated]].map(([t,arr])=>`<div class="grid-col"><div class="grid-title">${t}</div><div class="grid-2x4">${arr.map(smallTile).join('')}</div></div>`).join('');}
function renderShop(category=null){const cats=[...new Set(PRODUCTS.map(p=>p.category))].sort();document.getElementById('category-filter').innerHTML=`<a href="#shop" class="${!category?'active':''}">ALL</a>`+cats.map(c=>`<a href="#shop/${encodeURIComponent(c)}" class="${c===category?'active':''}">${c}</a>`).join('');const items=category?PRODUCTS.filter(p=>p.category===category):PRODUCTS;document.getElementById('shop-grid').innerHTML=items.length?items.map(productTile).join(''):'<div class="shop-empty">No products in this category.</div>';}
function renderProduct(slug){const p=bySlug[slug];if(!p){location.hash='#shop';return;}document.getElementById('product-detail').innerHTML=`<div class="pd-img"><img src="${img(p)}" alt="${p.name}"></div><div class="pd-info"><a class="back-link" href="#shop">← Back to shop</a><div class="pd-cat">${p.category}</div><h1>${p.name}</h1><div class="pd-price">${money(p.price)}</div><div class="pd-desc">${p.description}</div><div class="product-actions"><button class="btn-primary" onclick="addToCart('${p.slug}')">ADD TO CART</button><a class="btn-secondary" href="#cart">VIEW CART</a></div></div>`;}
function addToCart(slug){if(bySlug[slug]&&!cart.includes(slug))cart.push(slug);saveCart();location.hash='#cart';}
function removeFromCart(slug){cart=cart.filter(s=>s!==slug);saveCart();renderCart();}
function renderCart(){const items=cart.map(s=>bySlug[s]).filter(Boolean);const total=items.reduce((a,p)=>a+p.price,0);document.getElementById('cart-content').innerHTML=items.length?`${items.map(p=>`<div class="cart-row"><img src="${img(p)}" alt="${p.name}"><div class="ci-name">${p.name}</div><div class="ci-price">${money(p.price)}</div><button class="remove-btn" onclick="removeFromCart('${p.slug}')">Remove</button></div>`).join('')}<div class="cart-total"><span>Total</span><span>${money(total)}</span></div><button class="btn-primary checkout-button" onclick="alert('Payment will be connected after the live storefront review.')">CHECKOUT</button>`:'<div class="empty-state">Your cart is empty.</div>';}
function show(id){document.querySelectorAll('.spa-page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0);}
function route(){const h=location.hash.replace(/^#/,'')||'home';const parts=h.split('/');if(parts[0]==='shop'){show('page-shop');renderShop(parts[1]?decodeURIComponent(parts.slice(1).join('/')):null);}else if(parts[0]==='product'){show('page-product');renderProduct(parts[1]);}else if(parts[0]==='cart'){show('page-cart');renderCart();}else{show('page-home');if(parts[0]==='moments')setTimeout(()=>document.getElementById('moments').scrollIntoView(),0);}}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();const routeName=r.dataset.route;if(routeName==='home')location.hash='#home';else if(routeName==='moments'){location.hash='#home';setTimeout(()=>document.getElementById('moments').scrollIntoView({behavior:'smooth'}),50);}else location.hash='#'+routeName;}const c=e.target.closest('[data-category]');if(c){e.preventDefault();location.hash='#shop/'+encodeURIComponent(c.dataset.category);}});
window.addEventListener('hashchange',route);renderHome();saveCart();route();
