COLLECTION_BLUEPRINTS = [
    {
        "code": "silver-legacy-25",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Silver Legacy",
        "milestone": "25th Anniversary",
        "status": "design_queue",
        "palette": ["warm white", "soft silver", "pearl grey", "subtle champagne"],
        "style": "European editorial minimalism with a fine metallic border and restrained monogram.",
        "signature": "Interlocking anniversary monogram with a small 25 mark.",
    },
    {
        "code": "golden-vows-50",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Golden Vows",
        "milestone": "50th Anniversary",
        "status": "design_queue",
        "palette": ["ivory", "champagne gold", "warm cream", "deep wine accent"],
        "style": "Formal luxury dinner aesthetic with generous white space and elegant gold detailing.",
        "signature": "Refined 50-year crest suitable for invitation, menu, envelope liner and table cards.",
    },
    {
        "code": "renewed-in-como",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Renewed in Como",
        "milestone": "Vow Renewal",
        "status": "design_queue",
        "palette": ["lake blue", "warm white", "soft gold", "olive green"],
        "style": "Destination vow-renewal suite inspired by Lake Como architecture and water, without tourist-postcard styling.",
        "signature": "Minimal lake-line motif carried across all thirteen pieces.",
    },
    {
        "code": "fifty-after-dark",
        "occasion": "Milestone Birthdays",
        "name": "Fifty After Dark",
        "milestone": "50th Birthday",
        "status": "design_queue",
        "palette": ["deep burgundy", "warm ivory", "champagne gold"],
        "style": "Sophisticated evening celebration with strong editorial typography and no funeral-black dominance.",
        "signature": "Large elegant 50 integrated into the composition rather than used as a generic badge.",
    },
    {
        "code": "sixty-on-the-riviera",
        "occasion": "Milestone Birthdays",
        "name": "Sixty on the Riviera",
        "milestone": "60th Birthday",
        "status": "design_queue",
        "palette": ["Mediterranean navy", "bright white", "gold", "coral accent"],
        "style": "Modern Riviera dinner-party identity: architectural, bright and celebratory.",
        "signature": "Riviera arch motif used on invitation, menu, place card and envelope liner.",
    },
    {
        "code": "seventy-in-bloom",
        "occasion": "Milestone Birthdays",
        "name": "Seventy in Bloom",
        "milestone": "70th Birthday",
        "status": "design_queue",
        "palette": ["bright fuchsia", "soft blush", "ivory", "gold"],
        "style": "Elegant botanical celebration with contemporary flowers and substantial white space, never old-fashioned floral stationery.",
        "signature": "Modern floral frame with a discreet 70 monogram and matching envelope liner pattern.",
    },
]
