COLLECTION_BLUEPRINTS = [
    {
        "code": "paris-editorial",
        "occasion": "Weddings",
        "name": "Paris Editorial",
        "milestone": "Wedding",
        "status": "prototype_prepress_passed",
        "palette": ["warm white", "deep wine", "champagne gold", "soft graphite"],
        "style": "Editorial Parisian restraint with EB Garamond display typography, generous white space and open champagne-gold corner marks.",
        "signature": "Open gold corner system with paired hairlines and a restrained central gold mark.",
        "prepress_theme": "paris-editorial",
    },
    {
        "code": "amalfi-luce",
        "occasion": "Weddings",
        "name": "Amalfi Luce",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["bright warm white", "bougainvillea coral", "olive green", "champagne gold"],
        "style": "Luminous Mediterranean destination suite with architectural negative space rather than postcard imagery.",
        "signature": "Fine Amalfi arch motif with a discreet bougainvillea accent and airy typography.",
        "prepress_theme": "amalfi-luce",
    },
    {
        "code": "monaco-regatta",
        "occasion": "Weddings",
        "name": "Monaco Regatta",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["bright white", "Mediterranean navy", "lacquer red", "champagne gold"],
        "style": "Crisp modern formal wedding identity inspired by Monaco tailoring, yachts and clean Riviera geometry without black dominance.",
        "signature": "Precise navy line system with a small red-gold ceremonial accent.",
        "prepress_theme": "monaco-regatta",
    },
    {
        "code": "como-sereno",
        "occasion": "Weddings",
        "name": "Como Sereno",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["soft white", "lake blue", "sage olive", "soft gold"],
        "style": "Quiet Lake Como luxury using water, stone and garden tones with refined villa-inspired spacing.",
        "signature": "Minimal lake-line motif carried consistently through invitation, menu, program and liner.",
        "prepress_theme": "como-sereno",
    },
    {
        "code": "provence-rose",
        "occasion": "Weddings",
        "name": "Provence Rose",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["clean white", "dusty rose", "muted lavender", "champagne gold"],
        "style": "Contemporary French garden stationery with substantial white space and no old-fashioned watercolor-border treatment.",
        "signature": "Sparse modern botanical corners paired with strong editorial names and fine gold rules.",
        "prepress_theme": "provence-rose",
    },
    {
        "code": "santorini-aegean",
        "occasion": "Weddings",
        "name": "Santorini Aegean",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["bright white", "Aegean blue", "coral red", "soft gold"],
        "style": "Bright Greek destination identity built from geometric architecture, sunlight and sea color rather than tourist photography.",
        "signature": "Aegean arch-and-sun line motif with disciplined blue typography and a small coral accent.",
        "prepress_theme": "santorini-aegean",
    },
    {
        "code": "riviera-garden",
        "occasion": "Weddings",
        "name": "Riviera Garden",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["clean white", "bright fuchsia", "leaf green", "champagne gold"],
        "style": "Celebratory botanical Riviera suite with modern flowers, strong white space and fashion-editorial composition.",
        "signature": "Asymmetric floral punctuation rather than a full floral frame, with a minimal gold structural grid.",
        "prepress_theme": "riviera-garden",
    },
    {
        "code": "vienna-champagne",
        "occasion": "Weddings",
        "name": "Vienna Champagne",
        "milestone": "Wedding",
        "status": "design_queue",
        "palette": ["soft ivory", "champagne", "deep burgundy", "pearl grey"],
        "style": "Formal European evening stationery with classical proportion translated into a clean contemporary layout.",
        "signature": "Fine ceremonial crest geometry and champagne rules without heavy vintage ornamentation.",
        "prepress_theme": "vienna-champagne",
    },
    {
        "code": "silver-legacy-25",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Silver Legacy",
        "milestone": "25th Anniversary",
        "status": "design_queue",
        "palette": ["warm white", "soft silver", "pearl grey", "subtle champagne"],
        "style": "European editorial minimalism with a fine metallic border and restrained monogram.",
        "signature": "Interlocking anniversary monogram with a small 25 mark.",
    },
    {
        "code": "golden-vows-50",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Golden Vows",
        "milestone": "50th Anniversary",
        "status": "design_queue",
        "palette": ["ivory", "champagne gold", "warm cream", "deep wine accent"],
        "style": "Formal luxury dinner aesthetic with generous white space and elegant gold detailing.",
        "signature": "Refined 50-year crest suitable for invitation, menu, envelope liner and table cards.",
    },
    {
        "code": "renewed-in-como",
        "occasion": "Wedding Anniversaries & Vow Renewals",
        "name": "Renewed in Como",
        "milestone": "Vow Renewal",
        "status": "design_queue",
        "palette": ["lake blue", "warm white", "soft gold", "olive green"],
        "style": "Destination vow-renewal suite inspired by Lake Como architecture and water, without tourist-postcard styling.",
        "signature": "Minimal lake-line motif carried across all thirteen pieces.",
    },
    {
        "code": "fifty-after-dark",
        "occasion": "Milestone Birthdays",
        "name": "Fifty After Dark",
        "milestone": "50th Birthday",
        "status": "design_queue",
        "palette": ["deep burgundy", "warm ivory", "champagne gold"],
        "style": "Sophisticated evening celebration with strong editorial typography and no funeral-black dominance.",
        "signature": "Large elegant 50 integrated into the composition rather than used as a generic badge.",
    },
    {
        "code": "sixty-on-the-riviera",
        "occasion": "Milestone Birthdays",
        "name": "Sixty on the Riviera",
        "milestone": "60th Birthday",
        "status": "design_queue",
        "palette": ["Mediterranean navy", "bright white", "gold", "coral accent"],
        "style": "Modern Riviera dinner-party identity: architectural, bright and celebratory.",
        "signature": "Riviera arch motif used on invitation, menu, place card and envelope liner.",
    },
    {
        "code": "seventy-in-bloom",
        "occasion": "Milestone Birthdays",
        "name": "Seventy in Bloom",
        "milestone": "70th Birthday",
        "status": "design_queue",
        "palette": ["bright fuchsia", "soft blush", "ivory", "gold"],
        "style": "Elegant botanical celebration with contemporary flowers and substantial white space, never old-fashioned floral stationery.",
        "signature": "Modern floral frame with a discreet 70 monogram and matching envelope liner pattern.",
    },
]
