"""Small, explicit translation layer for the storefront UI."""

LANGUAGES = {
    "en": "English", "de": "Deutsch", "fr": "Français", "it": "Italiano",
    "es": "Español", "ru": "Русский", "el": "Ελληνικά", "pl": "Polski", "he": "עברית",
}

BASE = {
    "meta": "Premium digital wedding stationery by Love for Love.",
    "shop": "Shop", "collections": "Collections", "about": "Our studio", "cart": "Cart",
    "preview": "Development preview — payments remain disabled until the final products and Stripe are approved.",
    "hero_kicker": "Editorial wedding stationery",
    "hero_title": "A love story, beautifully told.",
    "hero_text": "Refined digital stationery inspired by the world's most romantic destinations.",
    "explore": "Explore collections", "view_shop": "View shop", "signature": "Signature collections",
    "signature_text": "Five distinct worlds, created as a coherent foundation for invitations, menus and wedding-day details.",
    "coming": "The first Love for Love collection is being prepared.",
    "coming_text": "Nothing is offered for sale until every file, description and download has passed our quality check.",
    "all_designs": "All designs", "all": "All", "empty_shop": "New original designs are in production.",
    "empty_shop_text": "The previous draft products have been removed from sale. The new verified collection will appear here.",
    "protected": "Protected delivery", "protected_text": "Downloads are unlocked only after confirmed payment.",
    "verified": "Verified files", "verified_text": "Every listing names the exact files included.",
    "premium": "Original design", "premium_text": "No unfinished or unapproved draft is sold.",
    "add": "Add to cart", "remove": "Remove", "total": "Total", "checkout": "Checkout",
    "empty_cart": "Your cart is empty.", "browse": "Browse the shop", "thank_you": "Thank you for your order.",
    "preview_download": "Preview mode: no payment was taken. These links are temporary test links.",
    "paid_download": "Payment confirmed. Your protected downloads are ready for a limited time.",
    "download": "Download", "continue": "Continue shopping", "payment_pending": "Payment not confirmed yet",
    "cancelled": "Checkout cancelled", "no_charge": "No charge was made. You can safely return to the shop.",
    "back": "Back to shop", "draft_label": "Collection in development",
}

TRANSLATIONS = {
    "en": BASE,
    "de": {**BASE,
        "meta":"Hochwertige digitale Hochzeitspapeterie von Love for Love.", "shop":"Shop", "collections":"Kollektionen", "about":"Unser Studio", "cart":"Warenkorb",
        "preview":"Entwicklungsvorschau — Zahlungen bleiben deaktiviert, bis Produkte und Stripe abschließend geprüft sind.", "hero_kicker":"Editoriale Hochzeitspapeterie", "hero_title":"Eine Liebesgeschichte, wunderschön erzählt.", "hero_text":"Edle digitale Papeterie, inspiriert von den romantischsten Orten der Welt.", "explore":"Kollektionen entdecken", "view_shop":"Zum Shop", "signature":"Signatur-Kollektionen", "signature_text":"Fünf eigenständige Welten als stimmige Grundlage für Einladungen, Menüs und Hochzeitspapeterie.", "coming":"Die erste Love for Love Kollektion wird vorbereitet.", "coming_text":"Nichts wird verkauft, bevor jede Datei, Beschreibung und jeder Download geprüft wurde.", "all_designs":"Alle Designs", "all":"Alle", "empty_shop":"Neue Originaldesigns sind in Arbeit.", "empty_shop_text":"Die früheren Entwürfe wurden aus dem Verkauf genommen. Die neue geprüfte Kollektion erscheint hier.", "protected":"Geschützte Lieferung", "protected_text":"Downloads werden erst nach bestätigter Zahlung freigeschaltet.", "verified":"Geprüfte Dateien", "verified_text":"Jedes Angebot nennt die exakt enthaltenen Dateien.", "premium":"Originaldesign", "premium_text":"Unfertige oder nicht freigegebene Entwürfe werden nicht verkauft.", "add":"In den Warenkorb", "remove":"Entfernen", "total":"Gesamt", "checkout":"Zur Kasse", "empty_cart":"Ihr Warenkorb ist leer.", "browse":"Zum Shop", "thank_you":"Vielen Dank für Ihre Bestellung.", "preview_download":"Vorschaumodus: Es wurde nichts berechnet. Diese Testlinks sind nur vorübergehend gültig.", "paid_download":"Zahlung bestätigt. Ihre geschützten Downloads stehen zeitlich begrenzt bereit.", "download":"Herunterladen", "continue":"Weiter einkaufen", "payment_pending":"Zahlung noch nicht bestätigt", "cancelled":"Kauf abgebrochen", "no_charge":"Es wurde nichts berechnet. Sie können sicher zum Shop zurückkehren.", "back":"Zurück zum Shop", "draft_label":"Kollektion in Entwicklung"},
    "fr": {**BASE, "shop":"Boutique", "collections":"Collections", "about":"Notre studio", "cart":"Panier", "preview":"Aperçu de développement — les paiements restent désactivés jusqu'à la validation finale.", "hero_kicker":"Papeterie de mariage éditoriale", "hero_title":"Une histoire d'amour, magnifiquement racontée.", "hero_text":"Papeterie numérique raffinée inspirée des destinations les plus romantiques.", "explore":"Découvrir les collections", "view_shop":"Voir la boutique", "signature":"Collections signature", "signature_text":"Cinq univers cohérents pour invitations, menus et détails du mariage.", "coming":"La première collection Love for Love est en préparation.", "coming_text":"Rien n'est vendu avant la vérification complète de chaque fichier et téléchargement.", "all_designs":"Tous les modèles", "all":"Tous", "empty_shop":"De nouveaux modèles originaux sont en création.", "empty_shop_text":"Les anciens brouillons ont été retirés de la vente. La collection vérifiée apparaîtra ici.", "protected":"Livraison protégée", "protected_text":"Téléchargements disponibles uniquement après paiement confirmé.", "verified":"Fichiers vérifiés", "verified_text":"Chaque fiche indique précisément les fichiers inclus.", "premium":"Création originale", "premium_text":"Aucun brouillon inachevé ou non approuvé n'est vendu.", "add":"Ajouter au panier", "remove":"Supprimer", "total":"Total", "checkout":"Commander", "empty_cart":"Votre panier est vide.", "browse":"Voir la boutique", "thank_you":"Merci pour votre commande.", "download":"Télécharger", "continue":"Continuer mes achats", "payment_pending":"Paiement non confirmé", "cancelled":"Commande annulée", "no_charge":"Aucun montant n'a été débité.", "back":"Retour à la boutique", "draft_label":"Collection en création"},
    "it": {**BASE, "shop":"Negozio", "collections":"Collezioni", "about":"Il nostro studio", "cart":"Carrello", "hero_kicker":"Cartoleria nuziale editoriale", "hero_title":"Una storia d'amore, raccontata con bellezza.", "hero_text":"Raffinata cartoleria digitale ispirata alle destinazioni più romantiche.", "explore":"Scopri le collezioni", "view_shop":"Vai al negozio", "signature":"Collezioni iconiche", "signature_text":"Cinque mondi coordinati per inviti, menu e dettagli del matrimonio.", "coming":"La prima collezione Love for Love è in preparazione.", "coming_text":"Nulla viene venduto prima del controllo completo di file e download.", "all_designs":"Tutti i design", "all":"Tutti", "empty_shop":"Nuovi design originali sono in lavorazione.", "empty_shop_text":"Le vecchie bozze sono state ritirate. La collezione verificata apparirà qui.", "protected":"Consegna protetta", "verified":"File verificati", "premium":"Design originale", "add":"Aggiungi al carrello", "remove":"Rimuovi", "total":"Totale", "checkout":"Acquista", "empty_cart":"Il carrello è vuoto.", "browse":"Vai al negozio", "thank_you":"Grazie per il tuo ordine.", "download":"Scarica", "continue":"Continua gli acquisti", "cancelled":"Acquisto annullato", "no_charge":"Non è stato effettuato alcun addebito.", "back":"Torna al negozio", "draft_label":"Collezione in sviluppo"},
    "es": {**BASE, "shop":"Tienda", "collections":"Colecciones", "about":"Nuestro estudio", "cart":"Carrito", "hero_kicker":"Papelería nupcial editorial", "hero_title":"Una historia de amor, bellamente contada.", "hero_text":"Papelería digital refinada inspirada en los destinos más románticos.", "explore":"Explorar colecciones", "view_shop":"Ver tienda", "signature":"Colecciones emblemáticas", "signature_text":"Cinco universos coordinados para invitaciones, menús y detalles de boda.", "coming":"La primera colección Love for Love está en preparación.", "coming_text":"Nada se vende antes de verificar cada archivo y descarga.", "all_designs":"Todos los diseños", "all":"Todos", "empty_shop":"Estamos creando nuevos diseños originales.", "empty_shop_text":"Los borradores anteriores se retiraron de la venta. La colección verificada aparecerá aquí.", "protected":"Entrega protegida", "verified":"Archivos verificados", "premium":"Diseño original", "add":"Añadir al carrito", "remove":"Eliminar", "total":"Total", "checkout":"Finalizar compra", "empty_cart":"Tu carrito está vacío.", "browse":"Ver tienda", "thank_you":"Gracias por tu pedido.", "download":"Descargar", "continue":"Seguir comprando", "cancelled":"Compra cancelada", "no_charge":"No se ha realizado ningún cargo.", "back":"Volver a la tienda", "draft_label":"Colección en desarrollo"},
    "ru": {**BASE, "shop":"Магазин", "collections":"Коллекции", "about":"О студии", "cart":"Корзина", "preview":"Режим разработки — оплата отключена до окончательной проверки товаров и Stripe.", "hero_kicker":"Авторская свадебная полиграфия", "hero_title":"История любви, рассказанная красиво.", "hero_text":"Изысканные цифровые дизайны, вдохновлённые самыми романтичными местами мира.", "explore":"Смотреть коллекции", "view_shop":"В магазин", "signature":"Фирменные коллекции", "signature_text":"Пять самостоятельных миров для приглашений, меню и деталей свадебного дня.", "coming":"Первая коллекция Love for Love готовится к выпуску.", "coming_text":"Ничего не поступит в продажу, пока каждый файл, описание и загрузка не пройдут проверку.", "all_designs":"Все дизайны", "all":"Все", "empty_shop":"Новые авторские дизайны находятся в работе.", "empty_shop_text":"Старые черновые товары сняты с продажи. Здесь появится новая проверенная коллекция.", "protected":"Защищённая доставка", "protected_text":"Файлы открываются только после подтверждённой оплаты.", "verified":"Проверенные файлы", "verified_text":"На странице товара точно указано всё содержимое.", "premium":"Авторский дизайн", "premium_text":"Незаконченные и неутверждённые материалы не продаются.", "add":"Добавить в корзину", "remove":"Удалить", "total":"Итого", "checkout":"Оформить заказ", "empty_cart":"Корзина пуста.", "browse":"Перейти в магазин", "thank_you":"Спасибо за заказ.", "preview_download":"Тестовый режим: оплата не списывалась. Ссылки действуют временно.", "paid_download":"Оплата подтверждена. Защищённые ссылки готовы и действуют ограниченное время.", "download":"Скачать", "continue":"Продолжить покупки", "payment_pending":"Оплата пока не подтверждена", "cancelled":"Оформление отменено", "no_charge":"Списание не производилось. Можно безопасно вернуться в магазин.", "back":"Вернуться в магазин", "draft_label":"Коллекция в разработке"},
    "el": {**BASE, "shop":"Κατάστημα", "collections":"Συλλογές", "about":"Το στούντιο", "cart":"Καλάθι", "hero_kicker":"Εκδοτική γαμήλια γραφική ύλη", "hero_title":"Μια ιστορία αγάπης, όμορφα ειπωμένη.", "explore":"Δείτε τις συλλογές", "view_shop":"Στο κατάστημα", "signature":"Χαρακτηριστικές συλλογές", "coming":"Η πρώτη συλλογή Love for Love ετοιμάζεται.", "all_designs":"Όλα τα σχέδια", "all":"Όλα", "empty_shop":"Νέα πρωτότυπα σχέδια δημιουργούνται.", "protected":"Προστατευμένη παράδοση", "verified":"Ελεγμένα αρχεία", "premium":"Πρωτότυπος σχεδιασμός", "add":"Προσθήκη στο καλάθι", "remove":"Αφαίρεση", "total":"Σύνολο", "checkout":"Ολοκλήρωση αγοράς", "empty_cart":"Το καλάθι είναι άδειο.", "browse":"Στο κατάστημα", "download":"Λήψη", "back":"Πίσω στο κατάστημα", "draft_label":"Συλλογή σε ανάπτυξη"},
    "pl": {**BASE, "shop":"Sklep", "collections":"Kolekcje", "about":"Nasze studio", "cart":"Koszyk", "hero_kicker":"Edytorska papeteria ślubna", "hero_title":"Historia miłości, pięknie opowiedziana.", "explore":"Poznaj kolekcje", "view_shop":"Przejdź do sklepu", "signature":"Kolekcje autorskie", "coming":"Pierwsza kolekcja Love for Love jest przygotowywana.", "all_designs":"Wszystkie wzory", "all":"Wszystkie", "empty_shop":"Powstają nowe autorskie wzory.", "protected":"Chroniona dostawa", "verified":"Sprawdzone pliki", "premium":"Oryginalny projekt", "add":"Dodaj do koszyka", "remove":"Usuń", "total":"Razem", "checkout":"Do kasy", "empty_cart":"Koszyk jest pusty.", "browse":"Przejdź do sklepu", "download":"Pobierz", "back":"Wróć do sklepu", "draft_label":"Kolekcja w przygotowaniu"},
    "he": {**BASE, "shop":"חנות", "collections":"קולקציות", "about":"הסטודיו שלנו", "cart":"סל", "hero_kicker":"עיצובי חתונה בסגנון מגזיני", "hero_title":"סיפור אהבה, מסופר ביופי.", "hero_text":"עיצובים דיגיטליים מעודנים בהשראת המקומות הרומנטיים בעולם.", "explore":"לצפייה בקולקציות", "view_shop":"לחנות", "signature":"קולקציות מובילות", "coming":"הקולקציה הראשונה של Love for Love בהכנה.", "all_designs":"כל העיצובים", "all":"הכול", "empty_shop":"עיצובים מקוריים חדשים נמצאים בהכנה.", "protected":"מסירה מוגנת", "verified":"קבצים בדוקים", "premium":"עיצוב מקורי", "add":"הוספה לסל", "remove":"הסרה", "total":"סה״כ", "checkout":"לתשלום", "empty_cart":"הסל ריק.", "browse":"לחנות", "download":"הורדה", "back":"חזרה לחנות", "draft_label":"קולקציה בפיתוח"},
}

# Complete the customer-facing copy for locales whose compact definitions above
# intentionally reuse the common structure.
TRANSLATIONS["fr"].update({"meta":"Papeterie de mariage numérique haut de gamme par Love for Love.","preview_download":"Mode aperçu : aucun paiement n’a été effectué. Ces liens de test sont temporaires.","paid_download":"Paiement confirmé. Vos téléchargements protégés sont disponibles pour une durée limitée.","coming_text":"Rien n’est vendu avant la vérification de chaque fichier, description et téléchargement.","protected_text":"Les téléchargements sont accessibles uniquement après confirmation du paiement.","verified_text":"Chaque fiche indique exactement les fichiers inclus.","premium_text":"Aucun brouillon inachevé ou non approuvé n’est vendu.","signature_text":"Cinq univers cohérents pour invitations, menus et détails du mariage."})
TRANSLATIONS["it"].update({"meta":"Cartoleria digitale premium per matrimoni di Love for Love.","preview":"Anteprima di sviluppo — i pagamenti restano disattivati fino alla verifica finale.","protected_text":"I download si sbloccano solo dopo il pagamento confermato.","verified_text":"Ogni scheda indica esattamente i file inclusi.","premium_text":"Nessuna bozza incompleta o non approvata viene venduta.","preview_download":"Modalità anteprima: nessun pagamento è stato effettuato. I link di prova sono temporanei.","paid_download":"Pagamento confermato. I download protetti sono disponibili per un periodo limitato.","payment_pending":"Pagamento non ancora confermato"})
TRANSLATIONS["es"].update({"meta":"Papelería digital premium para bodas de Love for Love.","preview":"Vista de desarrollo — los pagos siguen desactivados hasta la verificación final.","protected_text":"Las descargas se activan solo tras confirmar el pago.","verified_text":"Cada ficha indica exactamente los archivos incluidos.","premium_text":"No se vende ningún borrador incompleto o no aprobado.","preview_download":"Modo de prueba: no se realizó ningún pago. Los enlaces son temporales.","paid_download":"Pago confirmado. Las descargas protegidas están disponibles por tiempo limitado.","payment_pending":"Pago aún no confirmado"})
TRANSLATIONS["el"].update({"meta":"Premium ψηφιακή γαμήλια γραφική ύλη από τη Love for Love.","preview":"Προεπισκόπηση ανάπτυξης — οι πληρωμές παραμένουν απενεργοποιημένες έως τον τελικό έλεγχο.","hero_text":"Εκλεπτυσμένα ψηφιακά σχέδια εμπνευσμένα από τους πιο ρομαντικούς προορισμούς.","signature_text":"Πέντε ολοκληρωμένοι κόσμοι για προσκλήσεις, μενού και λεπτομέρειες γάμου.","coming_text":"Τίποτα δεν πωλείται πριν ελεγχθεί κάθε αρχείο, περιγραφή και λήψη.","empty_shop_text":"Τα παλιά προσχέδια αποσύρθηκαν. Η νέα ελεγμένη συλλογή θα εμφανιστεί εδώ.","protected_text":"Οι λήψεις ενεργοποιούνται μόνο μετά από επιβεβαιωμένη πληρωμή.","verified_text":"Κάθε προϊόν αναφέρει ακριβώς τα αρχεία που περιλαμβάνει.","premium_text":"Δεν πωλούνται ημιτελή ή μη εγκεκριμένα προσχέδια.","thank_you":"Ευχαριστούμε για την παραγγελία σας.","preview_download":"Λειτουργία δοκιμής: δεν έγινε πληρωμή. Οι σύνδεσμοι είναι προσωρινοί.","paid_download":"Η πληρωμή επιβεβαιώθηκε. Οι προστατευμένες λήψεις είναι διαθέσιμες για περιορισμένο χρόνο.","continue":"Συνέχεια αγορών","payment_pending":"Η πληρωμή δεν έχει επιβεβαιωθεί ακόμη","cancelled":"Η αγορά ακυρώθηκε","no_charge":"Δεν έγινε χρέωση. Μπορείτε να επιστρέψετε με ασφάλεια στο κατάστημα."})
TRANSLATIONS["pl"].update({"meta":"Ekskluzywna cyfrowa papeteria ślubna Love for Love.","preview":"Podgląd roboczy — płatności są wyłączone do czasu końcowej weryfikacji.","hero_text":"Wyrafinowane projekty cyfrowe inspirowane najbardziej romantycznymi miejscami.","signature_text":"Pięć spójnych światów dla zaproszeń, menu i dodatków ślubnych.","coming_text":"Nic nie trafia do sprzedaży przed sprawdzeniem każdego pliku, opisu i pobrania.","empty_shop_text":"Poprzednie szkice wycofano ze sprzedaży. Nowa sprawdzona kolekcja pojawi się tutaj.","protected_text":"Pliki są odblokowywane dopiero po potwierdzeniu płatności.","verified_text":"Każda oferta dokładnie wymienia zawarte pliki.","premium_text":"Niedokończone lub niezatwierdzone szkice nie są sprzedawane.","thank_you":"Dziękujemy za zamówienie.","preview_download":"Tryb testowy: płatność nie została pobrana. Linki są tymczasowe.","paid_download":"Płatność potwierdzona. Chronione pliki są dostępne przez ograniczony czas.","continue":"Kontynuuj zakupy","payment_pending":"Płatność nie została jeszcze potwierdzona","cancelled":"Zakup anulowany","no_charge":"Nie pobrano opłaty. Możesz bezpiecznie wrócić do sklepu."})
TRANSLATIONS["he"].update({"meta":"עיצובי חתונה דיגיטליים יוקרתיים מבית Love for Love.","preview":"תצוגת פיתוח — התשלומים מושבתים עד לאישור הסופי.","signature_text":"חמישה עולמות שלמים להזמנות, תפריטים ופרטי יום החתונה.","coming_text":"דבר אינו נמכר לפני שכל קובץ, תיאור והורדה עוברים בדיקה.","empty_shop_text":"הטיוטות הקודמות הוסרו מהמכירה. הקולקציה המאושרת תופיע כאן.","protected_text":"ההורדות נפתחות רק לאחר אישור התשלום.","verified_text":"בכל מוצר מצוינים בדיוק הקבצים הכלולים.","premium_text":"טיוטות לא גמורות או לא מאושרות אינן נמכרות.","thank_you":"תודה על ההזמנה.","preview_download":"מצב בדיקה: לא בוצע תשלום. הקישורים זמניים.","paid_download":"התשלום אושר. ההורדות המוגנות זמינות לזמן מוגבל.","continue":"המשך קנייה","payment_pending":"התשלום עדיין לא אושר","cancelled":"הרכישה בוטלה","no_charge":"לא בוצע חיוב. אפשר לחזור בבטחה לחנות."})


def translate(language, key):
    return TRANSLATIONS.get(language, BASE).get(key, BASE.get(key, key))
