OCCASION_EDITOR_PROFILES = {
    "anniversary": {
        "title": "Anniversary & Vow Renewal Suite",
        "headline": "Celebrate the story you have built together",
        "primary_person_label": "Names",
        "primary_person_default": "Emma & James",
        "event_title_label": "Celebration title",
        "event_title_default": "25 Years Together",
        "invitation_heading": "Anniversary Celebration",
        "invitation_wording": "Together with their family, invite you to celebrate a milestone in their life together",
        "program_heading": "Celebration Program",
        "thank_you_heading": "Thank You",
        "thank_you_default": "Thank you for celebrating this milestone with us. Your presence makes this chapter even more meaningful.",
        "recommended_suite": [
            "Invitation",
            "Venue & Address Card",
            "RSVP Card",
            "Celebration Dinner Menu",
            "Table Number",
            "Guest Place Card",
            "Celebration Program",
            "Thank You Card",
            "Accommodation Card (optional)",
            "Guest Contact / Coordinator Card (optional)",
            "Dress Code Card (optional)",
            "Envelope Design (optional)",
            "Envelope Liner (optional)",
        ],
        "design_directions": [
            "silver-white for 25th anniversary",
            "champagne-gold for 50th anniversary",
            "deep ruby and warm ivory for romantic milestone dinners",
            "modern navy, cream and gold for formal vow renewals",
        ],
    },
    "milestone_birthday": {
        "title": "Milestone Birthday Suite",
        "headline": "A complete visual identity for a landmark birthday",
        "primary_person_label": "Celebrant name",
        "primary_person_default": "Sophia",
        "event_title_label": "Birthday / milestone",
        "event_title_default": "50th Birthday Celebration",
        "invitation_heading": "Birthday Invitation",
        "invitation_wording": "Join us for an unforgettable evening celebrating a remarkable milestone",
        "program_heading": "Evening Program",
        "thank_you_heading": "Thank You",
        "thank_you_default": "Thank you for making this celebration unforgettable. Your presence was the greatest gift.",
        "recommended_suite": [
            "Invitation",
            "Venue & Address Card",
            "RSVP Card",
            "Dinner / Party Menu",
            "Table Number",
            "Guest Place Card",
            "Evening Program",
            "Thank You Card",
            "Accommodation Card (optional)",
            "Guest Contact / Host Assistant Card (optional)",
            "Dress Code Card (optional)",
            "Envelope Design (optional)",
            "Envelope Liner (optional)",
        ],
        "design_directions": [
            "editorial ivory and gold",
            "deep burgundy and champagne",
            "Mediterranean blue and warm white",
            "bright fuchsia with refined metallic details",
            "minimal cream, red and gold",
        ],
    },
}
